### ISSUE TITLE
Track implementation of ZMQ store

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox#104]
This is an Issue to track the progress on the new 0MQ store implementation

All related PRs should point to this issue. 

Tasks that need to be compleated should also be documented here. 

@jptmoore can you supply information about the key generation required for 0MQ and I will get it added to the container manager ASAP

**Comment by jptmoore** [comment]
Thanks.

A key pair can be generated like this:

docker run -it zeromq/zeromq /usr/bin/curve_keygen

which produces something like:

This tool generates a CurveZMQ keypair, as two printable strings you can
use in configuration files or source code. The encoding uses Z85, which
is a base-85 format that is described in 0MQ RFC 32, and which has an
implementation in the z85_codec.h source used by this tool. The keypair
always works with the secret key held by one party and the public key
distributed (securely!) to peers wishing to connect to it.

== CURVE PUBLIC KEY ==
ZMZcRy1mgiK++fD8J7GSm+$1%kIwq6Ff!:ZnWR5=

== CURVE SECRET KEY ==
dkhMroQbN6WQqx^cRLMJQ0v-XwI]]#}^MWL-$e@a

The public key would go to drivers/apps and the secret key would go to the store.

**Comment by Toshbrown** [comment]
Is it one key per driver app store triplet? 

Would apps that use more than one store need a key for each?

**Comment by jptmoore** [comment]
> Is it one key per driver app store triplet?
Yes, the driver/app would have the same public key for a single store.

> Would apps that use more than one store need a key for each?
How is this handled now?

Something I didn't mention is how the client key exchange works on curve. Each client (a driver/app)  automatically exchanges its key pair with a server (store) at connection time as part of the curve protocol. Currently the client key pair is autogenerated by the client but can be overridden with supplied keys.

**Comment by cgreenhalgh** [comment]
I thought it would be like the current HTTPS setup, i.e. server (store) has a single private key with public key provided to clients by CM (trusted channel), so server is authenticated at connection level but client is not. 

Between app and store, all client access control is via macaroons, which the last time I looked were still pure bearer tokens (so no client authentication per se - all done at the application level), although requester authentication requirements could also be added here which would require some client authentication to be added in somewhere. 

But there is client authentication between container and CM (only) via a per-container secret injected into container at creation, but again checked at the application level (when container contacts CM) rather than the transport level. (unless things have changed)

**Comment by Toshbrown** [comment]
@cgreenhalgh Things have not changed, just some initial confusion. 

@jptmoore,

You can now see the ZMQ public key as docker secrets in apps and drivers (/run/secrets/ZMQ_PUBLIC_KEY) 

ZMQ secrete key is only available to stores (/run/secrets/ZMQ_SECRET_KEY) 

If you run databox in dev mode switching the to the core-container-manage to branch 104-zmq is all that's needed. Once https://github.com/me-box/databox/pull/100 is merged we can create a PR with pinned repos to track and test all the changes for this enhancement.

**Comment by Toshbrown** [comment]
Golang client is under devlopment over here https://github.com/Toshbrown/goZestClient

**Comment by Toshbrown** [comment]
I've started updating the go library see [Toshbrown/lib-go-databox](https://github.com/Toshbrown/lib-go-databox)

examples of using it are here [Toshbrown/driver-tplink-smart-plug](https://github.com/Toshbrown/driver-tplink-smart-plug/blob/master/src/app.go#L72)

### Todo

- [x] add observer API 
- [x] add all endpoints 
- [x] tidy and document the API exposed to App and driver developers.
