### ISSUE TITLE
databox does not start in dev mode

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#146]
hello,
I used the latest source code,and I run the ./databox-start dev ,but there was no starting the server.

![tocon1](https://user-images.githubusercontent.com/29420329/31482123-e64cc3f0-af61-11e7-9290-e33eddea9471.png)

**Comment by Toshbrown** [comment]
Hi, 

Looks like line 10 of utils is the problem, It looks like it has been included in error. Does deleting line 10 fix the problems? 

Cheers 

Tosh

**Comment by tsh-box** [comment]
line 10,is where?

**Comment by sevenEng** [comment]
Hi,

the error message points to here [line 10](https://github.com/me-box/databox/blob/master/scripts/utils.sh#L10), a quick solution, is to substitute `ME` with another variable name in that whole script. A search suggests that `ME` is reserved for bash internals and thus couldn't be reassigned, seems like a portability issue with bash default behavior across different distributions, see this [similar problem](https://serverfault.com/questions/259843/bash-script-error-test-line-5-uid-readonly-variable)

**Comment by Toshbrown** [comment]
/scripts/utils.sh

**Comment by tsh-box** [comment]
@Toshbrown ,@sevenEng  ,thanks you
Now It is work!

**Comment by tsh-box** [comment]
Could I question about the store-json?
1.) When install a driver,one store-json created and also mongo process also running as following as 
  [vagrant@databox ~]$  ps -aux | grep mongo
   root      6175  0.6  0.4 823980 18148 ?        Sl   22:37   0:00 mongod --dbpath database --fork --    logpath /dev/null --wiredTigerEngineConfigString=cache_size=50M

At this time,Can I access this runnig mongoDB by using tools(mongobooster) ?

2.) What is the purpose of the collection KV and timeseries in store-json?

3.) If I will be used the store-json to create the new collection for app(light-graph,os-monitor,twitter),Is it possible?

4.) When will be use the store-json-blob?

**Comment by Toshbrown** [comment]
Hi 

1) The mongo process is running in a container and does not expose the ports required to access MongoDB directly by design. If you want to see what is in there for debugging then, you can exec into the container and use the standard mongo tools. If you want to get access using another process than, it will need to be a databox app and use the store API.

2) The stores have to support many types of app. Some produce time series like data  (IoT sensors etc) or other just sore blobs of data associated with keys (driver settings for example).  Different operations are posable on different types of data so we expose different APIs. We are also planning to add a collection type for managing structured data. 

 3) I'm not sure what you mean here

4) store-json-blob is deprecated, is it still mentioned in the docs? 

Alos databox will be transitioning away from store-json and MongoDB in the medium term. [This](https://github.com/me-box/store-timeseries) will likely replace all stores under a new name. It is a custom storage engine based on https://github.com/mirage/irmin.

**Comment by tsh-box** [comment]
Thanks you for your answer.

Yes,I known about store-json-blob from  previous version.

May I ask you a question?
1.  Are the store-json and mongoDB seperatly?Not same?
2.  Could I add the new collection in store json by using store API?
3.  If I want to confirm the mongoDB Database or collection,I have to access by using the store API,
     Is it right?
For example,look like as following as]

        router :=mux.NewRouter()
	ui := http.StripPrefix("/ui", http.FileServer(http.Dir("./www/")))
	router.HandleFunc("/ui/data", getDataEndpoint).Methods("GET")
        router.HandleFunc("/status", getStatusEndpoint).Methods("GET")

**Comment by Toshbrown** [comment]
1. and 2. store-json is a container that has MongoDB running inside it. It exposes a limited rest API to read and write data. Apps can create new collections (data sources) using the [RegisterDatasource](https://github.com/me-box/lib-go-databox#RegisterDatasource) API call. Data is written using  [StoreJSONWriteKV](https://github.com/me-box/lib-go-databox#StoreJSONWriteKV) or [StoreJSONWriteTS](https://github.com/me-box/lib-go-databox#StoreJSONWriteTS) if your using the go api 

3. That code looks like a web server if you just want to access the data then [StoreJSONGetlatest](https://github.com/me-box/lib-go-databox#StoreJSONGetlatest) or [StoreJSONreadKV](https://github.com/me-box/lib-go-databox#StoreJSONreadKV) if your using lib-go-databox

Apps use a web server to display a UI, but for debugging you can print to standard out and use docker service logs [servicename] to see the output

**Comment by tsh-box** [comment]
@Toshbrown Thank you for answer !
