### ISSUE TITLE
databox-install-component builds all datastores

### ISSUE THREAD

**Issue by pooyadav** [me-box/databox#166]
Why is it necessary to build all available types of data stores when a driver just needs only one type - mentioned in its manifest? It would be nice to parse the manifest and build only required store. @tlodge

**Comment by Toshbrown** [comment]
@pooyadav happy to mearge prs that implement this.

**Comment by cgreenhalgh** [comment]
I think that the store(s) should be considered part of the core and downloaded or built by databox-start and databox-install-component shouldn't do anything with stores. E.g. current behaviour would seem to mean you get latest store build, not the version appropriate to the release you are using.

**Comment by mor1** [comment]
A store of the requested type (per manifest) should be instantiated when the app/driver is started.

In dev mode, you may wish to use a `:latest` tagged version so that you can develop your own stores (or debug existing stores, test PRs, etc).

Short to medium term, I think that we need to move to a world where non-developers only need to get hold of images (and perhaps start scripts for now, or other entry point in future), and even developers only need to have the repos of those things they're actually developing.

**Comment by Toshbrown** [comment]
in 0.3.0 this has been addressed and stores are built as part of the core.
