### ISSUE TITLE
In light graph app, what kind of data receive?

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#170]
Hello,
I have installed the driver-sensingkit and light graph app.
In this light graph,What data are shown in graph?

**Comment by yousefamar** [comment]
Light level over time, from the light sensor in your phone.

**Comment by tsh-box** [comment]
Light level means android phone's brightness level?
And only Light?
What is the purpose of selection of  the Mobile sensor data tab?

![ccc2](https://user-images.githubusercontent.com/29420329/31984241-ba2549a2-b99b-11e7-87a7-859b630e889f.png)

**Comment by yousefamar** [comment]
The sensingkit driver is general purpose, and can query any of those sensors, and write their data to its store. The light graph app only reads light sensor values from the store. Using the store API, you can create similar apps that read the data from one or more other mobile sensors in the store.

In other words, the driver can make data from any sensor available, but the app only asks for permission and uses the light sensor data. The driver can be used with any app that requires any mobile sensor data.

**Comment by tsh-box** [comment]
If I create new app that read the data from one or more other mobile sensors in the store,the sensingkit driver installation is also required even though when I have already installed the sensingkit driver for light graph app ?

Light sensor is where did receive the data from ?
I means the android phone of a screen brightness or light on/off ??

**Comment by yousefamar** [comment]
> If I create new app that read the data from one or more other mobile sensors in the store,the sensingkit driver installation is also required even though when I have already installed the sensingkit driver for light graph app ?

No you don't need to install it again, that driver's store can be queried by many apps at the same time.

> Light sensor is where did receive the data from ?
> I means the android phone of a screen brightness or light on/off ??

In most phones, there's an ambient light sensor above the screen (next to speaker, front-facing camera, and proximity sensor). This is usually used to automatically adjust screen brightness depending on your surroundings, e.g. if it's a sunny day, the screen gets brighter. You can affect the value on the graph by covering your phone with your hands, or holding it against a lamp or window.

**Comment by tsh-box** [comment]
Thanks you :)
 
And Is there no export service in light graph app?
I want to export the data of light.

**Comment by yousefamar** [comment]
The light graph doesn't export anything, but if you want you can with a few lines modify it to do so and re-build it. The light graph app is built using [our node library](https://github.com/me-box/lib-node-databox) which has documented API endpoints for exporting data. I recommend starting there. You can also take the twitter sentiment app, or os monitor app as examples (since they export), and don't forget to add [export permissions](https://github.com/me-box/app-twitter-sentiment/blob/master/databox-manifest.json#L79-L84) to the manifest.

**Comment by tsh-box** [comment]
hello, @yousefamar 
About to export light data,
Just only adding the following code into light graph app's manifest.json file,right?
  "export-whitelist": [    {
      "url": "https://export.amar.io/",
      "description": "Exports the calculated sentiment to amar.io"
    }
  ],

**Comment by yousefamar** [comment]
Not quite; that manifest entry is only so that your app can have permission to export to that URL. You would also need to modify the source code to export the data you want. [This](https://github.com/me-box/lib-node-databox#exportlongpolldestination-payload) is the function you want to use. E.g. in the most basic way, right before [this line](https://github.com/me-box/app-light-graph/blob/master/server.js#L55), you can add:

	subs.on('data', (hostname, datasourceID, data) => {
		databox.export.longpoll('https://export.amar.io/', { data: data });
	});

You can modify that as you see fit and rebuild the app — this will make it so that every time you get a subscription event, you export its payload (see app-twitter-sentiment does [the same thing](https://github.com/me-box/app-twitter-sentiment/blob/master/src/main.js#L133)).
