### ISSUE TITLE
UI lists  available datastreams provided by already installed or available drivers

### ISSUE THREAD

**Issue by pooyadav** [me-box/databox#182]
Currently, rootcatalog only provides list of the available stores, however, list of the the datastreams/ registered datasources is not listed. It would be nice to either provide an API for that so application developers find it easy to use those. For example, it may be possible a datastream could be provided by more than one driver, that will give users to choose appropriate driver from a list.

**Comment by Toshbrown** [comment]
This is how it currently works! Unless I'm missing something?

The root cat from the arbiter points the individual store cats so if you need to know what is available you just query the arbiter then query the stores. 

It was built this way so that the arbiter can filter out a store that you don't want to expose.

**Comment by pooyadav** [comment]
I think -  Move to v2 manifests (#40) should address some of this concern. But once there is better store api's, this should be an enhancement.

**Comment by Toshbrown** [comment]
What is the new functionality you are requesting is added?
