### ISSUE TITLE
No internal persistence mechanism for apps or drivers

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#189]
If drivers want to persist information, e.g. across restarts of the host or in future across updates to a driver, there is currently no way to do this. Or at least, if stores were actually persistent, one option would be to use a store.

But it would be nice (as in android) to have a persistent section of filesystem (like the /database volume of a store /should/ be) that would be shared across restarts/re-installs of the driver/app.

**Comment by Toshbrown** [comment]
I think it was envisaged the apps would have a read-only filesystem and store would provide a persistent storage mechanism.

cc/ @mor1

**Comment by mor1** [comment]
@Toshbrown Correct.
The plan had been that, for apps at least (and probably drivers, though they're already special), persistent storage is available only through the store, a component we provide so that we can ensure audit logging is provided (and, eventually, that all storage by an app is encrypted and so on, to enforce good practice).

**Comment by cgreenhalgh** [comment]
OK, using it's own store works.
