### ISSUE TITLE
No error details given after driver rejection

### ISSUE THREAD

**Issue by aid-oc** [me-box/databox#232]
Sorry if I'm missing something here but I'm having an issue where driver state infinitely cycles between preparing/rejected after trying to install. I've checked the logs of all running containers but cannot find any error messages to suggest what the problem is, the driver's Dockerfile has an entry command to just sleep. The Manifest has been accepted and I have compared it to others and cannot see any issues.

I have deleted all docker images/containers and recloned/ran databox but still have the same issue.

What causes a driver installation to be rejected?

Output of docker ps:

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/20520093/35247190-5f457504-ffc1-11e7-8495-eae4238f2cb5.png">

Network requests to https://localhost/api/driver/list flick between:

`[{"name":"driver-moves","type":"driver","desiredState":"ready","state":"rejected","status":"preparing"}]`
or
`[{"name":"driver-moves","type":"driver","desiredState":"ready","state":"preparing","status":"preparing"}]`

**Comment by Toshbrown** [comment]
This can be caused by a missing image (incorrectly tagged or named).

looks like you running in normal mode so your image needs to be tagged with the correct version 0.3.1 in your case. 

also `docker service logs [driver-name]` might give you some more info. 

The output of `docker service ls` and `docker images` would also help me debug the issue. 

It would also be useful to see the code is it available anywhere?

**Comment by aid-oc** [comment]
Thanks for the info, the issue was that the image was not tagged correctly. I was tagging it to match the version in the manifest and not the version that databox is running.
