### ISSUE TITLE
Remove platform dev mode dependency on node and npm

### ISSUE THREAD

**Issue by pooyadav** [me-box/databox#25]
I think it should include prerequisites  for ubuntu installation such as nodejs, npm and 
nodejs-legacy

**Comment by yousefamar** [comment]
Just out of interest (@Toshbrown maybe you know why), is there any reason why for platform dev mode we need to install node and npm on the host, and then the current directory is mounted to the container? Would it be feasible to have the `npm install` happen inside the container, then devs would only need to install Docker and nothing else? (Also it might backfire if we ever use packages with native code, since they might install on a different OS, then get mounted into a Linux container).

**Comment by Toshbrown** [comment]
@yousefamar historical I think. Can't find a valid reason for it.

**Comment by yousefamar** [comment]
Cool, then we might as well add this one to the TODO pile. :) Then even for devs, the only thing they need to install is Docker.

**Comment by pooyadav** [comment]
I also have the same thoughts, its easy to just run a docker container with
all installations.

**Comment by Toshbrown** [comment]
node and npm are now run in a container. So there is no need to install them locally 👍
