### ISSUE TITLE
Don't use env vars to pass secrets 

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox#3]
Passing the arbiter token and https certs via Env vars is not best practice. 

Docker 1.13 has support for secrets management see, [Manage sensitive data with Docker secrets](https://docs.docker.com/engine/swarm/secrets/) but this only works in swarm mode (I'm not sure how this will effect Databox). 

Another option could be to use something like [keywhiz](https://square.github.io/keywhiz/) or [sneaker](https://github.com/codahale/sneaker) or to roll our own into the arbiter.

**Comment by yousefamar** [comment]
Seems like we've finally reached [that bridge](https://github.com/me-box/databox-arbiter/issues/6#issuecomment-262211247)! Dockerode wraps working with secrets through the Docker Remote API too. I think it might be worth investigating Docker swarm mode in general, especially since it might come in handy in other areas (previous discussions with @mor1 regarding https://docs.docker.com/engine/swarm/how-swarm-mode-works/pki/ and managing certs). Perhaps @avsm might have some insights regarding possible ways to use this in our context.

**Comment by avsm** [comment]
Could just run a databox as a swarm-of-one as well.

**Comment by Toshbrown** [comment]
swarm-of-one implemented
