### ISSUE TITLE
Do we need a generic Databox import service/driver

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox#45]
We offer a generic databox export service is there a need fo a generic import service?

There are lots of IoT devkits and DIY IoT maker projects. If they wish to engage with the databox platform they need to build and maintain a databox driver. This is a significant overhead when all they want to do is push data into the databox. 

A generic driver could be written that offers an API for IoT devices to register with the databox and add data. A set of simple libs could then be built to give people an easy way to integrate new IoT devices into the databox platform. 

 A basic version of the API would look something like this:
     
**Register yourself with the databox:** 

     URL: /import/register 
     METHOD: POST
     DATA:      
          sensorType: Some sensor type (maybe from an ontology) 
          dataSpec: JSON schema describing the input data (or other suitable spec)
     RESPONSE:
          status:  success or fail
          sensorId: The databox generated sensor Id 
          macaroon: To be used to authenticate the device has write access

**Post your data:**

     URL: /import/[sensorId]/write
     METHOD: POST
     DATA:
          data: a JSON formatted string matching the dataSpec provided
          macaroon: as proof of ownership
     RESPONSE:
          status:  success or fail
          message: the reason for the error 

Other things like actuation support could also be added. 

Things that need more thought:

1. How do the IoT device discover the databox
2. The API should use HTTPS how do the IoT devices get the CM https public key 
3. Do we need to modify how the macaroons are used for this to work? @yousefamar 
4. How do we manage the data storage? We don't want a "data lake" for security reasons. 

This could tie in with @jptmoore and @tlodge's work on data specification 

@mor1 @haddadi @cgreenhalgh  any thorghts?

**Comment by mor1** [comment]
In general: sure. If it makes life easier for other parties to participate, why not.
Could (1) be handled simply by having Databox take a well-known name on the local WiFi network?
(2/3) need thought. 
Are there any concrete use cases driving this / acting as exemplars?

**Comment by yousefamar** [comment]
My thoughts:

Re. 2, I think that an IoT device that wants to push data can never know if a Databox is legit unless the user tells it or checks somehow (like when you pair a Bluetooth device and have to compare or put in a code). This doesn't seem to be a good solution here though, since we'd be trusting the IoT device to do the proper checks before streaming to an arbitrary destination or MITM. On the other hand, Databox requiring HTTPS when _pulling_ data was so that it can know that the IoT device is who it says it is (aside from encryption). I think while we don't enforce that yet, it was planned, at least for data that comes from e.g. Twitters servers as opposed to a device on the LAN. Is this still required for pushing data too? I'm not sure if it's possible to make those guarantees otherwise (short of introducing a central global CA).

---

Re. 3, I think the underlying system can stay as it is, but there would be other tweaks that are needed.

  1. Arbiter needs to be accessible from the outside (IIRC the internal port is already mapped to a host port, so it would just be a matter of perhaps reverse-proxying that to something like `/arbiter/:api` on whatever port that `/import` would be exposed on).
  2. As with the export service, the import service would get a shared secret that it validates macaroons with. The dashboard would then need some interface for granting permissions to these external drivers/importers.

The second point would also depend largely on how we would address your point (4). If the import service is kind of like a "mail-sorter" that just puts data in one of many headless stores, then it would be necessary I imagine. Normal drivers get wildcard permissions to their store by default, but since these stores are launched independently after some user interaction to specify that there's something that needs to make use of the import service, then they would need to specify permissions too.

That being said, if it's one store per sensorID/importer, then it might as well be one import-service per sensorID/importer, and at that point we might as well remove the middle-man and expose individual stores to the outside directly, giving us actual "external drivers", since stores log everything already too. 

**Pro:** Much simpler
**Con:** Potentially less secure (but either way we're not exposing the actual databases to the outside, but just store APIs, so we can just reject any GETs from the outside).

I'm inclined to think that the most ideal way would be to have a new driver manifest entry / permission requirement that makes it so that the system provisions for a driver to be accessible externally (allowing data to be pushed) and then have a swiss-army-knife driver that you config to accept request from certain URLs. Then you launch that (and its store) for every source you want to import from.

Equally we could have a generic "pull" driver that is configurable to query some URL and just stream the response into a store (perhaps even parse it if you config some known content-type or format like CSV or JSON).

**Pro:** Less hassle for sources that are literally just a web server that streams data.
**Con:** Less transparency, unless we allowing runtime tagging (since you don't actually have any metadata about what it's supposed to be pulling when building the driver).

**Comment by cgreenhalgh** [comment]
> If they wish to engage with the databox platform they need to build and maintain a databox driver. *This is a significant overhead* ...

So another approach would be to make building and maintaining a databox driver a very *small* overhead. 
E.g. some kind of web-based generic driver builder/downloader, that would also complement the SDK/editor. 
That would avoid breaking other parts of the security/abstraction model (e.g. the hard-to-define SLA  and the non-standard relationship to data sources for the generic driver,).

**Comment by Toshbrown** [comment]
I guess thats a no then ;-) closing
